### ISSUE TITLE
Documentation for merge of two GTFS files

### ISSUE THREAD

**Issue by ustroetz** [Jwuthri/gtfstools#1]
Is there already a method to merge two GTFS files? If so I am happy to contribute some documentation.

**Comment by Jwuthri** [comment]
Hi,

Yes of course, you have to play with the key ("service_id") in calendar and
calendar_dates
Maybe next week I'll push the module to merge 2 gtfs

2017-02-24 21:50 GMT+01:00 Uli Stroetz <notifications@github.com>:

**Comment by ustroetz** [comment]
Okay. Then I am looking forward to that push.
